In [2]:
# Loading the dataset using pandas

import pandas as pd

df = pd.read_excel('../data/customer_shopping_behavior_dataset.xlsx')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55.0,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,2,19.0,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2.0,Cash,Fortnightly
2,3,50.0,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23.0,Credit Card,Weekly
3,4,21.0,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49.0,PayPal,Weekly
4,5,45.0,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31.0,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23400 entries, 0 to 23399
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             23400 non-null  int64
 1   Age                     23166 non-null  float64
 2   Gender                  23049 non-null  str
 3   Item Purchased          23050 non-null  str
 4   Category                23049 non-null  str
 5   Purchase Amount (USD)   23166 non-null  float64
 6   Location                22800 non-null  str
 7   Size                    22962 non-null  str
 8   Color                   23108 non-null  str
 9   Season                  23061 non-null  str
 10  Review Rating           22388 non-null  float64
 11  Subscription Status     22953 non-null  str
 12  Shipping Type           22954 non-null  str
 13  Discount Applied        23044 non-null  str
 14  Promo Code Used         23060 non-null  str
 15  Previous Purchases      23166 non-null  float64
 16  Payment Method          23010 non-null  str
 17  Frequency of Purchases  22942 non-null  str
dtypes: float64(4), int64(1), str(13)
memory usage: 3.2 MB

In [19]:
# Summary statistics using .describe()
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,purchase_frequency_days
count,23400.000000,23166.000000,23166.000000,23049.000000,23166.000000,22725.000000
mean,11700.500000,44.181387,60.001425,3.739765,25.885436,88.954719
std,6755.142486,15.354311,69.977700,0.725251,15.871524,118.331626
min,1.000000,-5.000000,-20.000000,0.000000,-3.000000,7.000000
25%,5850.750000,31.000000,38.000000,3.200000,13.000000,14.000000
50%,11700.500000,44.000000,60.000000,3.800000,26.000000,30.000000
75%,17550.250000,57.000000,80.000000,4.300000,38.000000,90.000000
max,23400.000000,121.000000,9999.000000,9.900000,999.000000,365.000000

In [6]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

Customer ID                  0
Age                        234
Gender                     351
Item Purchased             350
Category                   351
Purchase Amount (USD)      234
Location                   600
Size                       438
Color                      292
Season                     339
Review Rating             1012
Subscription Status        447
Shipping Type              446
Discount Applied           356
Promo Code Used            340
Previous Purchases         234
Payment Method             390
Frequency of Purchases     458
dtype: int64

In [7]:
# Imputing missing values in Review Rating column with the median rating of the product category

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID                 0
Age                       234
Gender                    351
Item Purchased            350
Category                  351
Purchase Amount (USD)     234
Location                  600
Size                      438
Color                     292
Season                    339
Review Rating             351
Subscription Status       447
Shipping Type             446
Discount Applied          356
Promo Code Used           340
Previous Purchases        234
Payment Method            390
Frequency of Purchases    458
dtype: int64

In [9]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [11]:
# create a new column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [12]:
df[['age','age_group']].head(10)

    age    age_group
0  55.0  Middle-aged
1  19.0  Young Adult
2  50.0  Middle-aged
3  21.0  Young Adult
4  45.0  Middle-aged
5  46.0  Middle-aged
6  63.0       Senior
7  27.0  Young Adult
8  26.0  Young Adult
9  57.0  Middle-aged

In [13]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [15]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [17]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')